apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-statefulset
  labels:
    app: mongo
spec:
  serviceName: mongo-svc
  replicas: 1
  selector:
    matchLabels:
      app: mongo
      tier: data
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: mongo
        tier: data
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongo
          image: mongo:3 # Mengubah versi Docker image menjadi "mongo:3"
          imagePullPolicy: IfNotPresent # Menambahkan kebijakan penarikan gambar
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME_FILE
              value: "/etc/mongo-credentials/MONGO_ROOT_USERNAME"
            - name: MONGO_INITDB_ROOT_PASSWORD_FILE
              value: "/etc/mongo-credentials/MONGO_ROOT_PASSWORD"
          volumeMounts:
            - name: data-volume
              mountPath: /data/db
            - name: config-volume
              mountPath: /config
            - name: secret-volume
              mountPath: /etc/mongo-credentials
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: mongo-pvc
        - name: config-volume
          configMap:
            name: mongo-configmap
        - name: secret-volume
          secret:
            secretName: mongo-secret

