# PersistentVolume (PV) Configuration
apiVersion: v1 # Menentukan versi API Kubernetes yang digunakan.
kind: PersistentVolume # Mendefinisikan jenis sumber daya Kubernetes sebagai PersistentVolume.
metadata:
  name: mongo-pv # Menentukan nama PersistentVolume yang dibuat.
  labels:
    type: local # Menandai PersistentVolume dengan label "type: local".
spec:
  storageClassName: manual # Menentukan StorageClass yang digunakan untuk PersistentVolume.
  capacity:
    storage: 1Gi # Menentukan kapasitas penyimpanan sebesar 1Gi untuk PersistentVolume.
  accessModes:
    - ReadWriteOnce # Menentukan mode akses sebagai ReadWriteOnce (hanya dapat diakses untuk satu node secara bersamaan).
  hostPath:
    path: "/mnt/data/db" # Menentukan path host di dalam node sebagai lokasi penyimpanan PersistentVolume.

# PersistentVolumeClaim (PVC) Configuration
---
apiVersion: v1 # Menentukan versi API Kubernetes yang digunakan.
kind: PersistentVolumeClaim # Mendefinisikan jenis sumber daya Kubernetes sebagai PersistentVolumeClaim.
metadata:
  name: mongo-pvc # Menentukan nama PersistentVolumeClaim yang dibuat.
  labels:
    app: mongo # Menandai PersistentVolumeClaim dengan label "app: mongo".
spec:
  storageClassName: manual # Menentukan StorageClass yang digunakan untuk PersistentVolumeClaim.
  accessModes:
    - ReadWriteOnce # Menentukan mode akses sebagai ReadWriteOnce.
  resources:
    requests:
      storage: 1Gi # Menentukan permintaan penyimpanan sebesar 1Gi untuk PersistentVolumeClaim.
