apiVersion: v1 # Menentukan versi API Kubernetes yang digunakan.
kind: ConfigMap # Mendefinisikan jenis sumber daya Kubernetes yang dibuat, yaitu ConfigMap dalam kasus ini.

metadata:
  name: mongo-configmap # Menentukan nama ConfigMap yang dibuat.
  labels:
    app: mongo # Menentukan label untuk ConfigMap, mengasosiasikannya dengan aplikasi "mongo".

data:
  mongo.conf:
    | # Mengonfigurasi pengaturan penyimpanan MongoDB, menentukan jalur database.
    storage:
      dbPath: /data/db
