apiVersion: v1 # Menentukan versi API Kubernetes yang digunakan
kind: Service # Mendefinisikan jenis sumber daya Kubernetes sebagai Service
metadata:
  name: mongo-svc # Menentukan nama Service sebagai 'mongo-svc'
  labels:
    app: mongo # Menandai Service dengan 'app: mongo' untuk identifikasi
spec:
  ports:
    - port: 27017 # Menentukan port yang akan di-expose (27017 dalam hal ini)
  selector:
    tier: data # Mendefinisikan selector untuk mengidentifikasi Pods yang akan menerima lalu lintas
  clusterIP: None # Menentukan 'None' untuk clusterIP untuk menandakan headless service
