apiVersion: v1 # Menentukan versi API Kubernetes yang digunakan.
kind: Secret # Mendefinisikan bahwa ini adalah sumber daya Secret Kubernetes.
metadata:
  name: mongo-secret # Menentukan nama sumber daya Secret.
  labels:
    app: mongo # Memberi label 'mongo' pada sumber daya Secret ini.

data:
  MONGO_ROOT_PASSWORD: c3VwZXJzZWNyZXRwYXNzd29yZA== # Nilai terenkripsi Base64 dari kata sandi root MongoDB.
  MONGO_ROOT_USERNAME: YWRtaW4= # Nilai terenkripsi Base64 dari nama pengguna root MongoDB.
