apiVersion: v1 # Menentukan versi API Kubernetes yang digunakan.
kind: Service # Mendefinisikan jenis sumber daya Kubernetes sebagai Service
metadata:
  name: karsajobs-svc # Nama service
  labels:
    app: karsajobs # Memberi label pada service untuk kategorisasi
spec:
  type: NodePort # Jenis service: diakses secara eksternal melalui node port
  selector:
    tier: backend # Memilih pod berdasarkan label 'tier' yang bernilai 'backend'
  ports:
    - port: 8080 # Port tempat service mendengarkan secara internal
      name: karsajobs # Nama port
      protocol: TCP # Protokol yang digunakan (TCP dalam hal ini)
      nodePort: 30007 # Node port yang di-expose secara eksternal untuk mengakses service
