apiVersion: apps/v1 # Menentukan versi API Kubernetes yang digunakan.
kind: Deployment # Mendefinisikan jenis sumber daya Kubernetes sebagai Deployment
metadata:
  name: karsajobs-deploy # Nama deployment
  labels:
    app: karsajobs # Label untuk mengidentifikasi aplikasi
spec:
  replicas: 1 # Jumlah replika pod yang akan dijaga
  selector:
    matchLabels:
      app: karsajobs # Selector untuk mengidentifikasi aplikasi
      tier: backend # Selector untuk mengidentifikasi tier
  template:
    metadata:
      labels:
        app: karsajobs # Label untuk mengidentifikasi aplikasi
        tier: backend # Label untuk mengidentifikasi tier
    spec:
      containers:
        - name: karsajobs # Nama kontainer
          image: ghcr.io/diasutsman/karsajobs:latest # Lokasi gambar Docker
          ports:
            - containerPort: 8080 # Port yang akan di-expose di dalam kontainer
          env:
            - name: APP_PORT # Variabel lingkungan untuk port aplikasi
              value: "8080" # Nilai untuk port aplikasi
            - name: MONGO_HOST # Variabel lingkungan untuk host MongoDB
              value: mongo-svc # Nilai untuk host MongoDB
            - name: MONGO_USER # Variabel lingkungan untuk nama pengguna MongoDB
              valueFrom:
                secretKeyRef:
                  name: mongo-secret # Nama rahasia yang berisi kredensial MongoDB
                  key: MONGO_ROOT_USERNAME # Kunci dalam rahasia untuk nama pengguna MongoDB
            - name: MONGO_PASS # Variabel lingkungan untuk kata sandi MongoDB
              valueFrom:
                secretKeyRef:
                  name: mongo-secret # Nama rahasia yang berisi kredensial MongoDB
                  key: MONGO_ROOT_PASSWORD # Kunci dalam rahasia untuk kata sandi MongoDB
