apiVersion: apps/v1 # Menentukan versi API Kubernetes yang digunakan.
kind: Deployment # Mendefinisikan jenis sumber daya Kubernetes sebagai Deployment
metadata:
  name: karsajobs-ui-deploy # Nama Deployment
  labels:
    app: karsajobs-ui # Label untuk aplikasi
spec:
  replicas: 1 # Jumlah replika yang diinginkan untuk aplikasi
  selector:
    matchLabels:
      app: karsajobs-ui # Selector label untuk aplikasi
      tier: frontend # Selector label untuk tier (frontend dalam hal ini)
  template:
    metadata:
      labels:
        app: karsajobs-ui # Label untuk aplikasi dalam pod
        tier: frontend # Label untuk tier dalam pod
    spec:
      containers:
        - name: karsajobs-ui # Nama kontainer
          image: ghcr.io/diasutsman/karsajobs-ui:latest # Gambar Docker yang digunakan untuk kontainer
          ports:
            - containerPort: 8000 # Port yang akan di-expose dalam kontainer
          env:
            - name: VUE_APP_BACKEND
              value: "http://192.168.10.1:30007" # Variabel lingkungan untuk URL backend
