apiVersion: v1 # Menentukan versi API Kubernetes yang digunakan (v1 dalam kasus ini).
kind: Service # Menentukan jenis sumber daya Kubernetes yang didefinisikan (Service dalam kasus ini).
metadata:
  name: karsajobs-ui-svc # Nama service yang sedang dibuat.
  labels:
    app: karsajobs-ui # Label untuk aplikasi yang terkait dengan service ini.
spec:
  type: NodePort # Menentukan jenis service sebagai NodePort (diakses secara eksternal melalui port pada setiap node).
  selector:
    tier: frontend # Memilih pod yang akan dimasukkan dalam service ini berdasarkan label yang ditentukan.
  ports:
    - port: 8000 # Menentukan port tempat service akan mendengarkan dalam cluster.
      name: karsajobs-ui # Nama port yang digunakan oleh service.
      protocol: TCP # Menentukan protokol yang digunakan (TCP dalam kasus ini).
      nodePort: 30008 # Menentukan port pada node yang akan di-forward ke port service.
